name: TP 3.8 Archivage simplifié

on: [push]

permissions:
  contents: write

jobs:
  archivage:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Création du fichier rapport.txt
        run: date > rapport.txt

      - name: Commit et push du fichier
        run: |
          git config --global user.name dt231159
          git config --global user.email thao.dujardin@etu.univ-lehavre.fr
          git add rapport.txt
          git commit -m "Mise à jour automatique de rapport.txt" || echo "Aucun changement à commit"
          git push
